### ISSUE TITLE
Can you support the archive when the file get too big?

### ISSUE THREAD

**Issue by yangjunsss** [rifflock/lfshook#10]
As the title..

**Comment by rifflock** [comment]
You mean archiving log files when they get too big? I feel like that's an operation for the OS not for the log handler.

If `lfshook` were a direct logging tool I'd say sure, but since it's just a hook for `logrus` it doesn't really have that kind of access or functionality. If you want big files to be archived, or you want the log file to be rotated on a time-based instance, I'd recommend using something like `logrotate`. As far as I know that works to archive big logs without interrupting write access to the log file.

**Comment by mariussturm** [comment]
File rotation would actually be pretty handy. Yes on Unix machines one can use the system logrotation but on Windows it's not so easy. I would not implement this from scratch but providing an API that can use io.Writer instead of the the PathMap would solve this already. Then we could use something like https://github.com/lestrrat/go-file-rotatelogs to do the actual rotation.

**Comment by rifflock** [comment]
Not a bad point.
It'll take a bit of work to add that functionality, but I'm not opposed to doing it, or reviewing/merging a PR if someone else wants to put it together.
