### ISSUE TITLE
How to hide log from console?

### ISSUE THREAD

**Issue by seatonxx** [rifflock/lfshook#15]
my logs are going to files, but, in the same time, prints on screen, how can i disable the screen print?

^_^

**Comment by rifflock** [comment]
The hook doesn't write to console in any situation except where there is a failing in the hook or its configuration. The referenced [issue](https://github.com/sirupsen/logrus/issues/236) from the main repo is closed citing an issue with a bad revision? Are you using the latest versions of everything?

**Comment by RadhiFadlillah** [comment]
Hey @rifflock, sorry for bumping this old thread. Rather than issue, I just have a small question.

I'm using the latest `lfshook` and `logrus` and it prints the logs both to file and console. I rather like this, because it easier for me while developing and debugging app. However, according to the issue that you [referenced](https://github.com/sirupsen/logrus/issues/236), it is not supposed to happen. 

So, what is the default behavior for `lfshook` ? Is it only supposed to print to file, or both to file and console ?

Here is my code :

```go
package main

import (
	"github.com/rifflock/lfshook"
	"github.com/sirupsen/logrus"
)

func main() {
	// Create formatter
	consoleFormatter := logrus.TextFormatter{
		FullTimestamp:   true,
		TimestampFormat: "2006-01-02 15:04:05",
	}

	fileFormatter := logrus.TextFormatter{
		FullTimestamp:   true,
		TimestampFormat: "2006-01-02 15:04:05",
		DisableColors:   true,
	}

	// Set path to output file
	pathMap := lfshook.PathMap{
		logrus.InfoLevel:  "info.log",
		logrus.FatalLevel: "fatal.log",
		logrus.WarnLevel:  "warning.log",
	}

	logrus.SetFormatter(&consoleFormatter)
	logrus.StandardLogger().AddHook(lfshook.NewHook(pathMap, &fileFormatter))

	// Create some log
	logrus.Infoln("This is info")
	logrus.Warnln("This is warning")
	logrus.Fatalln("This is fatal")
}
```

**Comment by rifflock** [comment]
Hey @RadhiFadlillah! Sorry for taking a while to respond. I didn't get a notification because the issue is closed.

The standard behavior for `lfshook` is to print _only_ to file. I didn't put in any print statements that write to console, so any printing that shows up should be from the main `logrus` package.

The only calls to write to the console in `lfshook` are for errors, like when it can't open the file, etc.

**Comment by linbo** [comment]
@rifflock any option to disable writing to the console for error message?

**Comment by linbo** [comment]
Console output can be disabled by logrus , refer to [issue](https://github.com/Sirupsen/logrus/issues/328)
