### ISSUE TITLE
Formatting broken for non-TextFormatter formatters (PR7 reverted)

### ISSUE THREAD

**Issue by tim-gp** [rifflock/lfshook#23]
Hi, as discussed in the comments on #7 

Put the following into a new folder as `main.go` file and run `dep init` in the directory to pull in the latest sirupsen/lfshook.

```
package main

import (
	"os"

	logrus "github.com/Sirupsen/logrus"
	"github.com/rifflock/lfshook"
)

type json struct {
	a string
	b string
}

const logFile = "log.log"

func main() {
	baseLogger := logrus.New()
	baseLogger.Formatter = &logrus.JSONFormatter{TimestampFormat: "2006-01-02T15:04:05.000Z"}
	f, err := os.Open(logFile)
	if err != nil {
		f, err = os.Create(logFile)
	}
	hook := lfshook.NewHook(lfshook.PathMap{
		logrus.InfoLevel: f.Name(),
	})
	baseLogger.Hooks.Add(hook)
	logger := baseLogger.WithFields(logrus.Fields{
		"key": "value",
	})
	logger.Infof("test message", json{"1", "2"})
}
``` 

`go build` and then execute the binary.  Note that log.log does not contain `JSON`:
```
time="2017-11-22T13:04:47Z" level=info msg="test message%!(EXTRA main.json={1 2})" key=value
```

Next edit `Gopkg.toml` to pick up the #7 version of lfshook as follows (you can remove the sirupsen constraint):
```
[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "=1.2.0"
```

`dep ensure`, `go build` and then execute the binary. Note that the new line in log.log is `JSON`:
```
{"key":"value","level":"info","msg":"test message%!(EXTRA main.json={1 2})","time":"2017-11-22T13:09:13.052Z"}
```

**Comment by rifflock** [comment]
Okay, I understand the issue now, but it's not as simple as dropping that code back in.

When #7 was written, the hook didn't own its own Formatter. The hook was setup to do whatever the logger did, but to strip out color if the Logger was setup for text.

Now the logger can have its own Formatter, so if the Logger is using JSON, but the Hook is setup for Logstash (or anything other than JSON), I can't assume that the user wants the hook to write JSON.

I thought perhaps if I set it up to check  `if hook.formatter == txtFormatter && entry.Logger.Formatter.(type) != *logrus.TextFormatter`  then I could switch to the Logger's formatter, then revert at the end, but that seems like it would be unexpected behavior if you _wanted_ the default logging.

As I see it there are two _good_ solutions to this, though I'm definitely open to suggestions/PRs
1. I update the documentation to reflect that the hook will use the default TextFormatter unless explicitly otherwise using the `SetFormatter` function
2. I extend the constructor to have an optional Formatter parameter, so that the formatter can be set at instantiation.

@timgp, what do you think?

**Comment by tim-gp** [comment]
@rifflock thank you for this analysis.  I have a preference for the extended constructor, that will give good flexibility.

As @chris-garrett and @dem-waffles followed #7, do either of you have an opinion?

**Comment by rifflock** [comment]
With the merge of #24 the constructor now takes a `*logrus.Formatter` as its second parameter. Updating to version 2.0 should resolve this issue.
