### ISSUE TITLE
All tags point to the same commit

### ISSUE THREAD

**Issue by reidrac** [rifflock/lfshook#27]
All tags point to the same commit; so all releases are the same code, making them useless.

I'm tracking 1.7 and recent 2.0 release broke my code because 1.7 is now pointing to the same commit that was released 2.0.

Given that bd08170fdd38433e957c734d993ce56170fa1eaa was a breaking change that required major version bump, this is bad.

I'm not sure how did this happen!

**Comment by rifflock** [comment]
Yup, I was afraid that would happen. I tried to do a quick fix to #26 and it ended up having terrible consequences.

Looking into how to fix that now.

**Comment by rifflock** [comment]
v1.6 and v1.7 are now pointing at the correct commits. v1.5 and v1.4 couldn't be fixed because the commits are too old.

v2.0 is the breaking change. Sorry about accidentally pushing you onto that commit. I didn't realize it would even let me change the commit that a release was pointing to, let alone default it to master.
